### ISSUE TITLE
await provider.enable() is missing in documentation

### ISSUE THREAD

**Issue by gpersoon** [Squarelink-Inc/Squarelink-Docs#1]
When following the examples in https://docs.squarelink.com/#quickstart-web3,
it didn't work initially. The examples started working after adding:

After addding 
```JS
await provider.enable();
```

This is both important before:
1.  window.web3.eth.getAccounts().then(console.log)
2. sqlk.getName()

**Comment by theAlexPatin** [comment]
Hey @gpersoon, thanks for the find! I've just updated the docs!
